services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000 --ssl-keyfile key.pem --ssl-certfile cert.pem
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "443:443"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/csa_hello
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:17.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=csa_hello
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
